✨ Rework of the embed page and Streameth logo on player
streamethorg/streameth-platform pull request #718
Opened 2024-07-03 14:40 UTC by pblvrt

I reworked the embed page so that it can receive session or stage id as well as the current playback id. If session or stage id are passed then the player will display the relevant thumbnail. 

I also added a Streameth logo to the player for branding

2024-07-03 14:41 UTC, pblvrt commented on packages/app/app/[organization]/watch/page.tsx
> -        <div className="w-full bg-gray-300 aspect-video"></div>
!

2024-07-03 14:44 UTC, Mario-SO commented on packages/app/app/[organization]/watch/page.tsx
> -        <div className="w-full bg-gray-300 aspect-video"></div>
Could you be more descriptive? please

2024-07-03 14:51 UTC, Mario-SO approved these changes

2024-07-04 08:45 UTC, pblvrt commented
closes #716

2024-07-04 10:22 UTC, xannyxs requested changes
@greatsamist will comment with a bug

2024-07-04 10:32 UTC, greatsamist commented
Firstly, the player now displays the cover image on initial load, which is what we want. However, I'm uncertain about the player also displaying the cover image when the video is paused. Please take a look at the attached screenshot for reference.
<img width="1261" alt="image" src="https://github.com/streamethorg/streameth-platform/assets/88172184/c901e88b-134b-40b7-b3ce-414c2b23a9d5">

2024-07-04 11:53 UTC, xannyxs commented
> Firstly, the player now displays the cover image on initial load, which is what we want. However, I'm uncertain about the player also displaying the cover image when the video is paused. Please take a look at the attached screenshot for reference. <img alt="image" width="1261" src="https://private-user-images.githubusercontent.com/88172184/345796769-c901e88b-134b-40b7-b3ce-414c2b23a9d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTQyNzIsIm5iZiI6MTcyMDA5Mzk3MiwicGF0aCI6Ii84ODE3MjE4NC8zNDU3OTY3NjktYzkwMWU4OGItMTM0Yi00MGI3LWIzY2UtNDE0YzJiMjNhOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDExNTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYjYxYzIxOWJlOGJlZjAzZDliYzExYzNjZGE0M2Y2MzgwZmVmOWE4YjlmZjE0ZTlmMGUyY2MxZDM4OWYxN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DzkQ-AyGPcIOfB8g_DtsyqY1GFzXZPTBxNG4qAa5gJo">

It should show the frame it was paused at

2024-07-04 17:46 UTC, greatsamist approved these changes

2024-07-04 17:47 UTC, greatsamist approved these changes

2024-07-05 08:05 UTC, greatsamist commented
@xannyxs  Can we now merge this PR? The requested changes have been addressed.

2024-07-05 08:07 UTC, greatsamist approved these changes

2024-07-05 08:08 UTC, merged