✨ `/explore` page
streamethorg/streameth-platform pull request #845
Opened 2024-08-05 13:54 UTC by Mario-SO

# Pull Request Info

## Description
New `/explore` page

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published

## Screenshots (if appropriate):

## Additional context:

closes #641

2024-08-06 07:30 UTC, greatsamist requested changes

2024-08-06 07:30 UTC, greatsamist commented on packages/app/components/misc/FeaturedEventsData.tsx
> +const fetchEvents = cache(async () => {
A featuredEventData component is unnecessary. We already have dedicated services for event and organization queries within the services folder. Please utilize eventServices.tsx or OrganizationServices.tsx for fetching data.
usage 
```
const events = await fetchEvents({...query)
```

2024-08-06 07:30 UTC, greatsamist commented on packages/app/app/explore/page.tsx
>  const Home = ({ searchParams }: HomePageProps) => {
Can we use "Explore" instead of Home, since we are on the explore page?

2024-08-12 09:12 UTC, Mario-SO commented
The responsiveness of the tabs broke.

![CleanShot 2024-08-12 at 11 10 58](https://github.com/user-attachments/assets/bf678fda-6491-42ec-ba9b-12632702a6d2)

2024-08-13 11:54 UTC, greatsamist approved these changes

2024-08-13 11:58 UTC, merged